version: '3.8'

services:
  joson-pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: joson
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8123:8080